/**
 * detect-br-only.js — Finds PT posts that don't have EN/ES counterparts.
 * Creates a report file for the GitHub Actions workflow to open an issue.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const POSTS_DIR = join(__dirname, '..', 'src', 'content', 'posts');

function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const yaml = match[1];
  const data = {};

  const tkMatch = yaml.match(/^translationKey:\s*["']?([^"'\n]+)["']?\s*$/m);
  if (tkMatch) data.translationKey = tkMatch[1].trim();

  const localeMatch = yaml.match(/^locale:\s*["']?(\w+)["']?\s*$/m);
  if (localeMatch) data.locale = localeMatch[1].trim();

  const titleMatch = yaml.match(/^title:\s*["']?(.+?)["']?\s*$/m);
  if (titleMatch) data.title = titleMatch[1].trim();

  const draftMatch = yaml.match(/^draft:\s*(true|false)/m);
  data.draft = draftMatch ? draftMatch[1] === 'true' : false;

  return data;
}

function main() {
  const files = readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));

  // Group by translationKey
  const groups = {};
  for (const file of files) {
    const content = readFileSync(join(POSTS_DIR, file), 'utf-8');
    const data = parseFrontmatter(content);
    if (data.draft) continue;
    if (!data.translationKey) continue;

    if (!groups[data.translationKey]) groups[data.translationKey] = {};
    groups[data.translationKey][data.locale] = { file, title: data.title };
  }

  // Find groups missing EN or ES
  const brOnly = [];
  for (const [key, locales] of Object.entries(groups)) {
    if (locales.pt && (!locales.en || !locales.es)) {
      brOnly.push({
        translationKey: key,
        title: locales.pt.title,
        file: locales.pt.file,
        missingEn: !locales.en,
        missingEs: !locales.es,
      });
    }
  }

  if (brOnly.length === 0) {
    console.log('All PT posts have EN and ES translations. Nothing to do.');
    return;
  }

  console.log(`Found ${brOnly.length} PT posts without full translations:`);
  brOnly.forEach(p => {
    const missing = [p.missingEn && 'EN', p.missingEs && 'ES'].filter(Boolean).join(', ');
    console.log(`  - ${p.file} (missing: ${missing})`);
  });

  // Write report for GH Actions issue creation
  const report = `## Posts without EN/ES translations\n\n` +
    `Found **${brOnly.length}** PT posts that need translation:\n\n` +
    `| Post | Missing |\n|------|--------|\n` +
    brOnly.map(p => {
      const missing = [p.missingEn && 'EN', p.missingEs && 'ES'].filter(Boolean).join(', ');
      return `| ${p.title} | ${missing} |`;
    }).join('\n') +
    `\n\n_Generated by detect-br-only.js_`;

  writeFileSync('/tmp/br-only-report.md', report);
  writeFileSync('/tmp/br-only-count', String(brOnly.length));
}

main();
